#! /bin/sh 
# Arduino input
#AF=/dev/ttyACM0
CF=/etc/remote-control.cfg
AF=$(awk -F = '/dfile/ { print $2; }' < $CF)
#ALF=/home/amw/remote-control.log
ALF=$(awk -F = '/^logFile=/ { print $2; }' < $CF)
echo -n "t" > $AF
sleep .5
tail -1 $ALF
