#! /bin/sh 
# Arduino input
#AF=/dev/ttyACM0
#ALF=/home/amw/remote-control.log
CF=/etc/remote-control.cfg
AF=$(awk -F = '/dfile/ { print $2; }' < $CF)
ALF=$(awk -F = '/^logFile=/ { print $2; }' < $CF)
echo -n "a" > $AF
sleep .5
tail -1 $ALF
