#! /usr/bin/python
import sys

sys.path.append("/usr/local/sbin")
import logSerial

print "Content-Type: text/plain"
print

logSerial.init(logSerial.ReadConfig(logSerial.configFile))
log = open(logSerial.logFile, 'r');
log.seek(-1024, 2)
log.readline()
while True:
    x = log.readline()
    if not x:
	break
    print x,


# /usr/local/bin/heaterDump
#! /bin/sh 
# Arduino input
#AF=/dev/ttyACM0
#CF='/etc/remote-control.cfg'
#AF=$(awk -F = '/dfile/ { print $2; }' < $CF)
#ALF=/home/amw/remote-control.log
#ALF=$(awk -F = '/^logFile=/ { print $2; }' < $CF)
#logFile=/var/log/remote-control
#ALF='/var/log/remote-control'
#echo -n "b" > $AF
#sleep .5
#tail -7 $ALF

