#! /usr/bin/python
import sys

sys.path.append("/usr/local/sbin")
import logSerial

print "Content-Type: text/html"
print
print "<html><head><title>Heater Status</title></head>"
print "<body>"
print "<h1>Heater Status</h1>"

logSerial.init(logSerial.ReadConfig(logSerial.configFile))
log = open(logSerial.logFile, 'r');
log.seek(-1024, 2)
log.readline()
print"<table>\n"
L = []
PK = []
param = {}
while True:
    x = log.readline()
    if not x:
	break
    if 'Current Variables::' in x:
	continue
    x = x.rstrip()
    a = x.split(':', 1)
    a.reverse()
    if '=' in a[1]:
	vals = a[1].split('=')
	if not param.has_key(vals[0]):
	    PK.append(vals[0])
	param[vals[0]] = vals[1]
    else:
	L.append("<tr><td>" + "</td><td>".join(a) + "</td></tr>")

for k in PK:
    print "<tr><td>" + k + "</td><td>" + param[k] + "</td></tr>"

L.reverse()
for l in L:
    print l
print"</table>\n"

print "</body>"
print "</html>"

